services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: friends
    # ref: https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-LINE-PREFIX
    command: ["-c", "log_statement=all", "-c", "log_line_prefix=p:%p c:%c l:%l v:%v x:%x "]
    ports:
      - 5432:5432
