services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: friends
    ports:
      - 5432:5432
