services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: friends
    command: ["-c", "log_statement=all"]
    ports:
      - 5432:5432
